### ISSUE TITLE
ol@10.3.1 compatibility

### ISSUE THREAD

**Issue by marcomilone** [mmomtchev/ol-mbtiles#245]
Hello,
I think you already know, 
but I write you about this issue.

```bash
npm error While resolving: ol-mbtiles@3.1.0
npm error Found: ol@10.3.1
npm error node_modules/ol
npm error   ol@"^10.3" from the root project
npm error [...]
npm error Could not resolve dependency:
npm error peer ol@">=10.0.0 <10.3.0" from ol-mbtiles@3.1.0
npm error node_modules/ol-mbtiles
npm error   ol-mbtiles@"^3.1.0" from the root project
```

Thank you,

**Comment by mmomtchev** [comment]
Yes, I have a PR in the works, but since I was evicted from my home because of an extortion organized with the French police and some of the biggest companies in geospatial data, I am currently working from my van and I have limited access to electricity. I will try to merge it as soon as I can afford to do so.
